import asyncio
from playwright import async_api
from playwright.async_api import expect

async def run_test():
    pw = None
    browser = None
    context = None
    
    try:
        # Start a Playwright session in asynchronous mode
        pw = await async_api.async_playwright().start()
        
        # Launch a Chromium browser in headless mode with custom arguments
        browser = await pw.chromium.launch(
            headless=True,
            args=[
                "--window-size=1280,720",         # Set the browser window size
                "--disable-dev-shm-usage",        # Avoid using /dev/shm which can cause issues in containers
                "--ipc=host",                     # Use host-level IPC for better stability
                "--single-process"                # Run the browser in a single process mode
            ],
        )
        
        # Create a new browser context (like an incognito window)
        context = await browser.new_context()
        context.set_default_timeout(5000)
        
        # Open a new page in the browser context
        page = await context.new_page()
        
        # Navigate to your target URL and wait until the network request is committed
        await page.goto("http://localhost:3000/", wait_until="commit", timeout=10000)
        
        # Wait for the main page to reach DOMContentLoaded state (optional for stability)
        try:
            await page.wait_for_load_state("domcontentloaded", timeout=3000)
        except async_api.Error:
            pass
        
        # Iterate through all iframes and wait for them to load as well
        for frame in page.frames:
            try:
                await frame.wait_for_load_state("domcontentloaded", timeout=3000)
            except async_api.Error:
                pass
        
        # Interact with the page elements to simulate user flow
        # --> Assertions to verify final state
        frame = context.pages[-1]
        await expect(frame.locator('text=Portfolio').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Navigation Menu').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏠').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Home').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👤').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=About').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💼').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Experience').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⚡').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Skills').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚀').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Projects').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏆').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Certifications').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📝').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Blog').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💬').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Testimonials').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📧').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Contact').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=AT').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📊').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Analytics').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Hi, I\'m Aadarsh Thakur').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Full Stack Developer & Software Engineer').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=I craft exceptional digital experiences with modern technologies. Passionate about creating scalable solutions and bringing innovative ideas to life.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Get In Touch').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Download Resume').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=About Me').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=From a curious teenager who built his first "Hello World" program to a Computer Science Engineering Graduate and Backend Developer Intern at ASH-TECH SOLUTIONS, creating AI-powered solutions that impact real-world problems.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Started coding at 16 with Python, fascinated by how a few lines of code could solve complex problems. Built my first web scraper and was amazed by the power of automation.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Successfully graduated with Computer Science Engineering degree and joined ASH-TECH SOLUTIONS as a Backend Developer Intern, where I\'m currently working on cutting-edge backend systems and gaining real-world industry experience.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Created Farm-Ease, an AI-powered agricultural platform that helps 200+ farmers increase crop yield by 30% through intelligent recommendations and blockchain-based supply chain transparency.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Today, as a Backend Developer Intern at ASH-TECH SOLUTIONS, I\'m passionate about using technology to solve real-world problems, from smart city traffic management to sustainable agriculture. Every line of code is a step toward a better future.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Full Stack Development').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Experienced in building end-to-end web applications using modern technologies like React, Node.js, and cloud platforms.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Problem Solving').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Passionate about solving complex problems with clean, efficient code and innovative solutions that make a difference.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Performance Optimization').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Focused on creating fast, scalable applications with optimal user experience and cutting-edge performance.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Team Collaboration').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Strong believer in agile methodologies and collaborative development with excellent communication skills.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=DevOps & Automation').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Experienced with CI/CD pipelines, containerization, and cloud infrastructure for seamless deployment.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Continuous Learning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Always exploring new technologies and best practices to stay current with the rapidly evolving tech landscape.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=My Journey').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=My journey in technology began with curiosity and has evolved into a passion for creating meaningful digital experiences. I believe in writing clean, maintainable code and staying updated with the latest industry trends.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=When I\'m not coding, you\'ll find me exploring new technologies, contributing to open-source projects, or sharing knowledge with the developer community.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Technical Skills').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Python').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=HTML').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=CSS').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=React.js').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Tailwind CSS').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Framer Motion').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Machine Learning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Deep Learning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=TensorFlow').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=PyTorch').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Scikit-learn').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Pandas').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=NumPy').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Matplotlib').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=MySQL').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Git').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=GitHub').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Vercel').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=50+').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=3+').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=15+').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=100%').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Backend Developer Intern').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=ASH-TECH SOLUTIONS').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=07/2025 - Present').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Developing REST APIs using Node.js and MongoDB').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Optimizing backend systems for improved scalability and performance').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Collaborating with development team on system architecture').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Implementing best practices for backend development').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Working on real-world projects with industry standards').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Data Science Internship').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Internship Studio').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=10/2024').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Successfully completed Data Science Internship training, earning a Certificate of Completion.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Certificate Number: ISDSCT933504').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Gained hands-on experience in data analysis and visualization').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Completed comprehensive training in data science fundamentals').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=AI-ML Virtual Internship').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=AICTE').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=04/2024 - 06/2024').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Successfully completed a 4-week AI and Machine Learning course.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Earned Course Completion and Internship Certificates from AICTE and EduSkills').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Gained hands-on experience with key AI concepts and technologies').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Developed practical skills in machine learning applications').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Web Development Virtual Internship').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Bharat Intern').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=10/2023 - 11/2023').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Successfully completed a virtual internship program in Web Development.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Demonstrated skills in HTML, CSS, and JavaScript for frontend development').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Built responsive and interactive web applications').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Learned modern web development practices').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Bachelor of Technology (B.Tech)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=G L Bajaj Group of Institutions, Mathura').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=2021 - 2025').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Major: Computer Science Engineering').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=CGPA: 6.5/10').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Data Structures').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Algorithms').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Database Management').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Web Development').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Machine Learning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=12th Science (PCM)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Dashmesh Public School').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=2021').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Scored: 75%').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Strong foundation in Physics, Chemistry, and Mathematics').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Active participation in technical events and competitions').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=10th').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Holy Mary International School').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=2018').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Scored: 75%').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Excellent academic performance').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Participated in various extracurricular activities').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Skills & Expertise').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=A comprehensive collection of my technical skills and expertise across various domains').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Programming Languages').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Python').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=PROFICIENCY').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=JavaScript').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Web Development').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=HTML5').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=CSS3').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=React.js').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Tailwind CSS').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Framer Motion').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Machine Learning (Supervised, Unsupervised)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Deep Learning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Scikit-learn').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=TensorFlow').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=PyTorch').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Model Training & Evaluation').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Computer Vision').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=OpenCV').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=YOLOv7').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=ByteTrack').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Real-time Object Detection & Tracking').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Video Feed Analysis').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Data Science & Analytics').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Pandas').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=NumPy').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Matplotlib').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Tools & Platforms').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Git').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=GitHub').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Vercel').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=50+').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Projects Completed').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=3+').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Years Experience').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=15+').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Technologies').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=100%').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Client Satisfaction').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Experience & Education').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Internships').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Backend Developer Intern').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=ASH-TECH SOLUTIONS').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=07/2025 - Present').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Currently working as a Backend Developer Intern at ASH-TECH SOLUTIONS, developing REST APIs and optimizing backend systems for scalability.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Developing REST APIs using Node.js and MongoDB').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Optimizing backend systems for improved scalability and performance').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Collaborating with development team on system architecture').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Implementing best practices for backend development').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Working on real-world projects with industry standards').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Data Science Internship').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Internship Studio').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=10/2024').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Successfully completed Data Science Internship training, earning a Certificate of Completion.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Certificate Number: ISDSCT933504').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Gained hands-on experience in data analysis and visualization').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Completed comprehensive training in data science fundamentals').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=AI-ML Virtual Internship').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=AICTE').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=04/2024 - 06/2024').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Successfully completed a 4-week AI and Machine Learning course.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Earned Course Completion and Internship Certificates from AICTE and EduSkills').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Gained hands-on experience with key AI concepts and technologies').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Developed practical skills in machine learning applications').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Web Development Virtual Internship').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Bharat Intern').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=10/2023 - 11/2023').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Successfully completed a virtual internship program in Web Development.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Demonstrated skills in HTML, CSS, and JavaScript for frontend development').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Built responsive and interactive web applications').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Learned modern web development practices').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Bachelor of Technology (B.Tech)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=G L Bajaj Group of Institutions, Mathura').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=2021 - 2025').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Major: Computer Science Engineering').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• CGPA: 6.5/10').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Relevant Coursework: Data Structures, Algorithms, Database Management, Web Development, Machine Learning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=12th Science (PCM)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Dashmesh Public School').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=2021').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Scored: 75%').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Strong foundation in Physics, Chemistry, and Mathematics').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Active participation in technical events and competitions').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=10th').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Holy Mary International School').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=2018').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Scored: 75%').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Excellent academic performance').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=• Participated in various extracurricular activities').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Skills & Expertise').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=A comprehensive collection of my technical skills and expertise across various domains').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Programming Languages').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Python').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=PROFICIENCY').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=JavaScript').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Web Development').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=HTML5').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=CSS3').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=React.js').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Tailwind CSS').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Framer Motion').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Machine Learning (Supervised, Unsupervised)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Deep Learning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Scikit-learn').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=TensorFlow').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=PyTorch').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Model Training & Evaluation').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Computer Vision').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=OpenCV').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=YOLOv7').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=ByteTrack').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Real-time Object Detection & Tracking').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Video Feed Analysis').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Data Science & Analytics').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Pandas').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=NumPy').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Matplotlib').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Tools & Platforms').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Git').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=GitHub').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Vercel').first).to_be_visible(timeout=30000)
        await asyncio.sleep(5)
    
    finally:
        if context:
            await context.close()
        if browser:
            await browser.close()
        if pw:
            await pw.stop()
            
asyncio.run(run_test())
    